/* Central content catalogue. Pure data — imported by both server and
   client components, so keep it serialisable (no functions). */

/* Hero looks come in pairs: `img` is the piece worn by a model, `formImg`
   is the same piece presented on a tailor's dress form. Both are transparent
   cut-outs, so the stage can layer them into one diorama. `tint` colours the
   light wash behind each pair. */
export const HERO_SLIDES = [
  {
    id: "royal-blue-safari-suite",
    title: "Royal Blue Safari Suite",
    caption: "Safari suit · Short sleeve",
    img: "/images/royal-blue-safari-suite.png",
    formImg: "/images/royal-blue-safari-suite-form.png",
    width: 1024,
    height: 1024,
    formWidth: 736,
    formHeight: 736,
    tint: "rgba(47, 79, 143, 0.3)",
    alt: "Model wearing a royal blue short-sleeve safari suite",
    formAlt: "Royal blue safari suite displayed on a tailor's dress form",
    pin: {
      x: "50%",
      y: "58%",
      name: "Royal Blue Safari Suite",
      note: "Short sleeve · half canvas",
      price: 245000,
      productId: "royal-blue-safari-suite",
    },
  },
  {
    id: "cream-embroidered-kaftan",
    title: "Cream Embroidered Kaftan",
    caption: "Embroidered · Short kaftan",
    img: "/images/cream-offwhite-embroidered-kaftan-short.png",
    formImg: "/images/cream-offwhite-embroidered-kaftan-short-form.png",
    width: 922,
    height: 1152,
    formWidth: 736,
    formHeight: 920,
    tint: "rgba(194, 164, 125, 0.34)",
    alt: "Model wearing a cream off-white embroidered short kaftan",
    formAlt: "Cream embroidered short kaftan displayed on a tailor's dress form",
    pin: {
      x: "50%",
      y: "58%",
      name: "Cream Embroidered Kaftan",
      note: "Hand-trimmed neckline",
      price: 198000,
      productId: "cream-offwhite-embroidered-kaftan",
    },
  },
  {
    id: "deep-burgundy-safari-suit",
    title: "Deep Burgundy Safari Suit",
    caption: "Safari suit · Tailored",
    img: "/images/deep-burgundy-safari-suit-short.png",
    formImg: "/images/deep-burgundy-safari-suit-short-form.png",
    width: 1024,
    height: 1024,
    formWidth: 736,
    formHeight: 736,
    tint: "rgba(109, 36, 54, 0.3)",
    alt: "Model wearing a deep burgundy short safari suit",
    formAlt: "Deep burgundy safari suit displayed on a tailor's dress form",
    pin: {
      x: "50%",
      y: "58%",
      name: "Deep Burgundy Safari Suit",
      note: "Horn buttons · slim cut",
      price: 230000,
      productId: "deep-burgundy-safari-suit",
    },
  },
  {
    id: "medium-grey-high-collar",
    title: "Medium Grey High Collar",
    caption: "High collar · Patterned",
    img: "/images/medium-grey-high-collar-pattern.png",
    formImg: "/images/medium-grey-high-collar-pattern-form.png",
    width: 976,
    height: 1102,
    formWidth: 736,
    formHeight: 831,
    tint: "rgba(122, 122, 122, 0.3)",
    alt: "Model wearing a medium grey patterned high-collar tunic",
    formAlt: "Medium grey high-collar pattern displayed on a tailor's dress form",
    pin: {
      x: "50%",
      y: "58%",
      name: "Medium Grey High Collar",
      note: "Patterned weave · banded collar",
      price: 215000,
      productId: "medium-grey-high-collar",
    },
  },
  {
    id: "mustard-yellow-safari-suite",
    title: "Mustard Yellow Safari Suite",
    caption: "Safari suit · Statement",
    img: "/images/mustard-yellow-safari-suite-short.png",
    formImg: "/images/mustard-yellow-safari-suite-short-form.png",
    width: 1024,
    height: 1024,
    formWidth: 564,
    formHeight: 564,
    tint: "rgba(216, 161, 26, 0.32)",
    alt: "Model wearing a mustard yellow short safari suite",
    formAlt: "Mustard yellow safari suite displayed on a tailor's dress form",
    pin: {
      x: "50%",
      y: "58%",
      name: "Mustard Yellow Safari Suite",
      note: "Short sleeve · statement cut",
      price: 225000,
      productId: "mustard-yellow-safari-suite",
    },
  },
  {
    id: "off-white-long-line-kaftan",
    title: "Off-White Long-Line Kaftan",
    caption: "Long line · Flowing",
    img: "/images/off-white-long-line-kaftan-long.png",
    formImg: "/images/off-white-long-line-kaftan-long-form.png",
    width: 922,
    height: 1152,
    formWidth: 1080,
    formHeight: 1324,
    tint: "rgba(233, 227, 216, 0.5)",
    alt: "Model wearing an off-white long-line kaftan",
    formAlt: "Off-white long-line kaftan displayed on a tailor's dress form",
    pin: {
      x: "50%",
      y: "58%",
      name: "Off-White Long-Line Kaftan",
      note: "Ankle length · side slit",
      price: 175000,
      productId: "off-white-long-line-kaftan",
    },
  },
  {
    id: "dark-grey-safari-suite",
    title: "Dark Grey Safari Suite",
    caption: "Safari suit · Short sleeve",
    img: "/images/dark-grey-safari-suite-short-sleeve.png",
    formImg: "/images/dark-grey-safari-suite-short-sleeve-form.png",
    width: 1024,
    height: 1024,
    formWidth: 736,
    formHeight: 736,
    tint: "rgba(74, 74, 74, 0.3)",
    alt: "Model wearing a dark grey short-sleeve safari suite",
    formAlt: "Dark grey safari suite displayed on a tailor's dress form",
    pin: {
      x: "50%",
      y: "58%",
      name: "Dark Grey Safari Suite",
      note: "Short sleeve · soft shoulder",
      price: 190000,
      productId: "dark-grey-safari-suite",
    },
  },
];

export const LOOKBOOK = [
  {
    num: "01",
    label: "01 / Agbada",
    title: "Agbada\nCollections",
    copy: "The flowing centerpiece of Nigerian dress. Our agbada sets are cut generously so they drape and move, then finished with hand-stitched embroidery across the neckline and sleeves.",
    tags: ["Classic Agbada", "Embroidered", "Fitted Agbada"],
    cta: "Discover Agbada",
    img: "/images/charcoal-kaftan-long-sleeve.jpg",
    width: 1080,
    height: 1338,
    alt: "Model wearing a classic Nigerian agbada set",
  },
  {
    num: "02",
    label: "02 / Occasion",
    title: "Occasion\nSilks",
    copy: "Silk, lace and senator-style pieces for the moments that matter. Built with a structured shoulder and clean finish, so the silhouette stays sharp from the altar to the after-party.",
    tags: ["Senator", "Lace Two-Piece", "Silk Kaftan"],
    cta: "Explore Occasion Wear",
    img: "/images/offwhite-long-sleeve.jpg",
    width: 1080,
    height: 1324,
    alt: "Model in a silk occasion two-piece with structured shoulder",
  },
  {
    num: "03",
    label: "03 / Fabrics",
    title: "Heritage\nFabrics",
    copy: "Aso Oke woven on handlooms, Adire dyed in indigo baths, Ankara printed in bold wax. We work directly with weavers and dyers so every bolt carries its origin.",
    tags: ["Aso Oke", "Adire", "Ankara"],
    cta: "Shop Fabrics",
    img: "/images/dark-green-short-sleeved.jpg",
    width: 736,
    height: 831,
    alt: "Detail of handwoven Aso Oke cloth on a workbench",
  },
  {
    num: "04",
    label: "04 / Menswear",
    title: "Native\nMenswear",
    copy: "Senator, buba and sokoto, and embroidered caps to finish the look. The same traditional language, cut for a modern wardrobe that works Monday to Monday night.",
    tags: ["Senator", "Buba & Sokoto", "Caps"],
    cta: "View Menswear",
    img: "/images/burgundy-whine-safari-suit-berret-cap-short-sleeve.jpg",
    width: 736,
    height: 920,
    alt: "Native menswear set with matching embroidered cap",
  },
];

export const ESSENTIALS = [
  {
    shape: "tile--xl",
    idx: "01",
    title: "Aso Oke Agbada",
    sub: "Handwoven three-piece",
    img: "/images/cream-off-white-short-kaftan.jpg",
    width: 736,
    height: 806,
    alt: "Aso Oke agbada set",
    filter: "Agbada",
  },
  {
    shape: "tile--wide",
    idx: "02",
    title: "Ankara Prints",
    sub: "Bold wax statement sets",
    img: "/images/dark-brown-striped-suite-with-collar.jpg",
    width: 736,
    height: 693,
    alt: "Ankara print two-piece",
    filter: "Ankara",
  },
  {
    shape: "tile--tall",
    idx: "03",
    title: "Lace Occasion",
    sub: "Wedding & gala ready",
    img: "/images/burgundy-whine-safari-suite-short-sleeve.jpg",
    width: 736,
    height: 736,
    alt: "Embroidered occasion dress",
    filter: "Occasion",
  },
  {
    shape: "tile--tall",
    idx: "04",
    title: "Adire Indigo",
    sub: "Hand-dyed in Abeokuta",
    img: "/images/navy-blue-short-safari-suit.jpg",
    width: 736,
    height: 736,
    alt: "Adire indigo two-piece",
    filter: "Adire",
  },
  {
    shape: "tile--wide",
    idx: "05",
    title: "Silk Kaftans",
    sub: "Cut in our Lagos atelier",
    img: "/images/offwhite-kaftan-long.jpg",
    width: 736,
    height: 736,
    alt: "Silk kaftan cut in the Lagos atelier",
    filter: "Menswear",
  },
];

export const FILTERS = [
  "All",
  "Aso Oke",
  "Agbada",
  "Occasion",
  "Adire",
  "Ankara",
  "Menswear",
  "Accessories",
];

export const PRODUCTS = [
  {
    id: "royal-blue-safari-suite",
    name: "Royal Blue Safari Suite",
    cat: "Menswear",
    price: 245000,
    compareAt: null,
    badge: "New",
    rating: 5,
    img: "/images/royal-blue-safari-suite.png",
    altImg: "/images/royal-blue-safari-suite-form.png",
    width: 1024,
    height: 1024,
    alt: "Royal blue short-sleeve safari suite",
    swatches: ["#2f4f8f", "#14110f", "#c2a47d"],
    desc: "A royal blue safari suite cut short in the sleeve and half-canvased through the chest, so it holds its line without feeling stiff. Four patch pockets, horn buttons, and a clean banded collar.",
  },
  {
    id: "cream-offwhite-embroidered-kaftan",
    name: "Cream Embroidered Kaftan",
    cat: "Menswear",
    price: 198000,
    compareAt: null,
    badge: null,
    rating: 5,
    img: "/images/cream-offwhite-embroidered-kaftan-short.png",
    altImg: "/images/cream-offwhite-embroidered-kaftan-short-form.png",
    width: 922,
    height: 1152,
    alt: "Cream off-white embroidered short kaftan",
    swatches: ["#efe9df", "#c2a47d"],
    desc: "A short cream kaftan with hand-trimmed embroidery at the neckline and placket. Worn open over a vest or buttoned up — the piece that carries a whole evening.",
  },
  {
    id: "deep-burgundy-safari-suit",
    name: "Deep Burgundy Safari Suit",
    cat: "Menswear",
    price: 230000,
    compareAt: null,
    badge: null,
    rating: 5,
    img: "/images/deep-burgundy-safari-suit-short.png",
    altImg: "/images/deep-burgundy-safari-suit-short-form.png",
    width: 1024,
    height: 1024,
    alt: "Deep burgundy short safari suit",
    swatches: ["#6d2436", "#14110f"],
    desc: "Deep burgundy twill, slim through the body with a soft shoulder and horn buttons. Short sleeves keep it easy for Lagos heat; the colour keeps it formal.",
  },
  {
    id: "medium-grey-high-collar",
    name: "Medium Grey High Collar",
    cat: "Menswear",
    price: 215000,
    compareAt: null,
    badge: null,
    rating: 4,
    img: "/images/medium-grey-high-collar-pattern.png",
    altImg: "/images/medium-grey-high-collar-pattern-form.png",
    width: 976,
    height: 1102,
    alt: "Medium grey patterned high-collar tunic",
    swatches: ["#8b8b8b", "#1c1917", "#c2a47d"],
    desc: "A medium grey patterned weave finished with a banded high collar. Structured enough for the boardroom, quiet enough to wear every week.",
  },
  {
    id: "mustard-yellow-safari-suite",
    name: "Mustard Yellow Safari Suite",
    cat: "Menswear",
    price: 225000,
    compareAt: null,
    badge: "New",
    rating: 5,
    img: "/images/mustard-yellow-safari-suite-short.png",
    altImg: "/images/mustard-yellow-safari-suite-short-form.png",
    width: 1024,
    height: 1024,
    alt: "Mustard yellow short safari suite",
    swatches: ["#d8a11a", "#c2a47d", "#14110f"],
    desc: "Mustard yellow, short sleeved, and cut for people who do not blend in. The statement safari suit of the festive edit — lined, pressed and finished in our Lagos atelier.",
  },
  {
    id: "off-white-long-line-kaftan",
    name: "Off-White Long-Line Kaftan",
    cat: "Menswear",
    price: 175000,
    compareAt: null,
    badge: null,
    rating: 5,
    img: "/images/off-white-long-line-kaftan-long.png",
    altImg: "/images/off-white-long-line-kaftan-long-form.png",
    width: 922,
    height: 1152,
    alt: "Off-white long-line kaftan",
    swatches: ["#efe9df", "#c2a47d"],
    desc: "An ankle-length off-white kaftan with a fluid fall and side slits for movement. Featherweight, unlined through the body, and finished with a hand-rolled hem.",
  },
  {
    id: "dark-grey-safari-suite",
    name: "Dark Grey Safari Suite",
    cat: "Menswear",
    price: 190000,
    compareAt: 215000,
    badge: "Sale",
    rating: 4,
    img: "/images/dark-grey-safari-suite-short-sleeve.png",
    altImg: "/images/dark-grey-safari-suite-short-sleeve-form.png",
    width: 1024,
    height: 1024,
    alt: "Dark grey short-sleeve safari suite",
    swatches: ["#4a4a4a", "#14110f"],
    desc: "The everyday dark grey safari suite: short sleeve, soft shoulder, four working pockets. Cut generously enough to move in, tailored enough to meet a client in.",
  },
  {
    id: "aso-oke-set",
    name: "Aso Oke Yoruba Set",
    cat: "Aso Oke",
    price: 240000,
    compareAt: null,
    badge: "New",
    rating: 5,
    img: "/images/creame-offwite-kaftan-long-sleeve.jpg",
    altImg: "/images/cream-off-white-short-kaftan.jpg",
    width: 720,
    height: 900,
    alt: "Handwoven Aso Oke Yoruba set",
    swatches: ["#14110f", "#c2a47d", "#2f4f4f"],
    desc: "Handwoven Aso Oke cut into a relaxed buba and sokoto, finished with a matching gelee or cap. Every set is loomed in Iseyin and tailored in our Lagos atelier.",
  },
  {
    id: "embroidered-agbada",
    name: "Embroidered Agbada",
    cat: "Agbada",
    price: 285000,
    compareAt: null,
    badge: null,
    rating: 5,
    img: "/images/off-white-kaftan-simple-empbroidery.jpg",
    altImg: "/images/charcoal-kaftan-long-sleeve.jpg",
    width: 736,
    height: 1079,
    alt: "Embroidered agbada three-piece with matching cap",
    swatches: ["#f4f2ef", "#c2a47d", "#1c1917"],
    desc: "A generously cut three-piece agbada with hand-stitched neckline embroidery, inner buba, and a fitted sokoto. Drapes cleanly over the shoulders.",
  },
  {
    id: "lace-occasion-gown",
    name: "Lace Occasion Gown",
    cat: "Occasion",
    price: 395000,
    compareAt: 440000,
    badge: "Sale",
    rating: 5,
    img: "/images/burgundy-short-sleeve-safari-suite.jpg",
    altImg: "/images/burgundy-whine-safari-suite-short-sleeve.jpg",
    width: 735,
    height: 882,
    alt: "Structured lace occasion gown",
    swatches: ["#c2a47d", "#7d2f43"],
    desc: "Structured lace two-piece with a sculpted shoulder and full-length skirt. Built for weddings, receptions and the after-party.",
  },
  {
    id: "adire-indigo-ensemble",
    name: "Adire Indigo Ensemble",
    cat: "Adire",
    price: 185000,
    compareAt: null,
    badge: null,
    rating: 4,
    img: "/images/navy-blue-kaftan-long-sleeve.jpg",
    altImg: "/images/navy-blue-short-safari-suit.jpg",
    width: 736,
    height: 1353,
    alt: "Indigo Adire ensemble hand-dyed in Abeokuta",
    swatches: ["#1f3a5f", "#f4f2ef"],
    desc: "Tied and dyed by hand in Abeokuta, then cut into a flowing two-piece. No two panels of the indigo pattern are ever identical.",
  },
  {
    id: "senator-three-piece",
    name: "Senator Three-Piece",
    cat: "Menswear",
    price: 225000,
    compareAt: null,
    badge: null,
    rating: 5,
    img: "/images/grey-long-kaftan-elegan-embroidery.jpg",
    altImg: "/images/burgundy-whine-safari-suit-berret-cap-short-sleeve.jpg",
    width: 736,
    height: 1342,
    alt: "Senator three-piece native menswear with cap",
    swatches: ["#14110f", "#2f4f4f", "#5c5651"],
    desc: "A clean-cut senator tunic with side slit, matching trousers and an embroidered cap. The everyday native piece, done properly.",
  },
  {
    id: "ankara-wax-two-piece",
    name: "Ankara Wax Two-Piece",
    cat: "Ankara",
    price: 120000,
    compareAt: null,
    badge: "New",
    rating: 4,
    img: "/images/butter-cream-dark-brown-long-safari-suit.jpg",
    altImg: "/images/dark-brown-striped-suite-with-collar.jpg",
    width: 736,
    height: 736,
    alt: "Bold Ankara wax print two-piece set",
    swatches: ["#c2a47d", "#7d2f43", "#2f4f4f"],
    desc: "Bold wax print worked into a peplum top and wrap skirt. Lined at the bodice so the print sits smooth against the body.",
  },
  {
    id: "indigo-adire-wrap",
    name: "Indigo Adire Wrap",
    cat: "Adire",
    price: 78000,
    compareAt: null,
    badge: null,
    rating: 5,
    img: "/images/navy-blue-safari-suite-long-sleeve.jpg",
    altImg: "/images/navy-blue-kaftan-long-sleeve.jpg",
    width: 736,
    height: 736,
    alt: "Indigo Adire wrap dress",
    swatches: ["#1f3a5f"],
    desc: "A versatile Adire wrap that works as a dress, a kimono or a beach layer. Softened through three washes before it leaves the atelier.",
  },
  {
    id: "asooke-beaded-clutch",
    name: "Aso Oke Beaded Clutch",
    cat: "Accessories",
    price: 46000,
    compareAt: null,
    badge: null,
    rating: 5,
    img: "/images/off-white-cream-long-stich-trimed.jpg",
    altImg: "/images/cream-off-white-short-kaftan.jpg",
    width: 500,
    height: 500,
    alt: "Beaded Aso Oke clutch bag",
    swatches: ["#c2a47d", "#14110f"],
    desc: "Hand-beaded Aso Oke clutch with a suede lining — sized for a phone, cards and lipstick.",
  },
  {
    id: "embroidered-occasion-blouse",
    name: "Embroidered Occasion Blouse",
    cat: "Occasion",
    price: 145000,
    compareAt: null,
    badge: null,
    rating: 4,
    img: "/images/cream-short-sleeved-kaftan.jpg",
    altImg: "/images/burgundy-short-sleeve-safari-suite.jpg",
    width: 736,
    height: 918,
    alt: "Embroidered occasion blouse",
    swatches: ["#f4f2ef", "#c2a47d"],
    desc: "Cotton-silk blouse with hand embroidery at the neckline and cuffs. Pairs with our iroki skirt or a tailored trouser.",
  },
  {
    id: "silk-kaftan",
    name: "Silk Kaftan",
    cat: "Menswear",
    price: 165000,
    compareAt: 189000,
    badge: "Sale",
    rating: 5,
    img: "/images/dark-burgundy-kaftan.jpg",
    altImg: "/images/offwhite-kaftan-long.jpg",
    width: 736,
    height: 920,
    alt: "Silk kaftan cut in the Lagos atelier",
    swatches: ["#1c1917", "#c2a47d"],
    desc: "A weightless silk kaftan with a mandarin collar and side slits — the piece for long evenings outdoors.",
  },
  {
    id: "adire-kimono-set",
    name: "Adire Kimono Set",
    cat: "Adire",
    price: 132000,
    compareAt: null,
    badge: null,
    rating: 4,
    img: "/images/green-long-kaftan.jpg",
    altImg: "/images/navy-blue-safari-suite-long-sleeve.jpg",
    width: 736,
    height: 690,
    alt: "Adire kimono set in indigo",
    swatches: ["#1f3a5f", "#f4f2ef"],
    desc: "Long kimono over a fitted inner dress, both cut from the same indigo bolt so the pattern runs continuously.",
  },
  {
    id: "handwoven-cap",
    name: "Handwoven Fila Cap",
    cat: "Accessories",
    price: 35000,
    compareAt: null,
    badge: null,
    rating: 5,
    img: "/images/muster-yellow-short-sleeve-safari-suit.jpg",
    altImg: "/images/grey-long-kaftan-elegan-embroidery.jpg",
    width: 564,
    height: 564,
    alt: "Handwoven fila cap",
    swatches: ["#14110f", "#c2a47d"],
    desc: "The finishing touch: a handwoven fila in Aso Oke, blocked to hold its shape wash after wash.",
  },
  {
    id: "lace-two-piece",
    name: "Lace Two-Piece",
    cat: "Occasion",
    price: 210000,
    compareAt: null,
    badge: null,
    rating: 5,
    img: "/images/grey-short-sleeve-safari-suit.jpg",
    altImg: "/images/burgundy-short-sleeve-safari-suite.jpg",
    width: 736,
    height: 736,
    alt: "Lace two-piece occasion outfit",
    swatches: ["#c2a47d", "#7d2f43"],
    desc: "Corded lace over a satin lining, cut as a peplum and skirt. alterations included on every order.",
  },
];

export const STORY = {
  eyebrow: "Our Story",
  title: "Crafted With Heritage",
  copy: "FASH began in Lagos with a simple idea: that the clothes we grew up seeing deserve to be made at the highest level. We work with weavers, dyers and embroiderers across Nigeria, then cut and finish every piece in our own atelier.",
  stats: [
    { value: 12, suffix: "", label: "Years of craft" },
    { value: 30, suffix: "+", label: "Artisan partners" },
    { value: 96, suffix: "%", label: "Repeat clients" },
  ],
  floatA: {
    img: "/images/grey-long-sleeve-simple-emboidery.jpg",
    width: 736,
    height: 672,
    alt: "Close detail of handwoven Aso Oke fabric",
  },
  floatB: {
    img: "/images/long-sleeve-dark-green-safari-suit.jpg",
    width: 736,
    height: 831,
    alt: "Model in a festive Nigerian look",
  },
};

export const HERO_STATS = [
  { dt: "Designs", value: 86 },
  { dt: "Fabrics", value: 34 },
  { dt: "Tailors", value: 24 },
];

export const REVIEWS = [
  {
    rating: 5,
    quote:
      "My agbada arrived two days early and the fit was exact. The embroidery is cleaner than pieces I have paid triple for in London.",
    name: "Chidinma O.",
    meta: "Agbada · London",
  },
  {
    rating: 5,
    quote:
      "They took my measurements over WhatsApp, cut the dress to fit, and handled two alterations without complaint. It felt like a private tailor.",
    name: "Emeka A.",
    meta: "Occasion wear · Lagos",
  },
  {
    rating: 5,
    quote:
      "The Adire is the real thing — you can tell it was tied and dyed by hand. I get stopped every time I wear it.",
    name: "Funke B.",
    meta: "Adire · Abeokuta",
  },
  {
    rating: 5,
    quote:
      "Third order this year. Consistent quality, honest pricing, and the caps finish every outfit properly.",
    name: "Tunde O.",
    meta: "Menswear · Abuja",
  },
  {
    rating: 5,
    quote:
      "Booked a styling session before my wedding party. They pulled fabrics I would never have chosen and every piece landed.",
    name: "Amaka N.",
    meta: "Styling session · Port Harcourt",
  },
  {
    rating: 4,
    quote:
      "Delivery to Ibadan took an extra day, but the lace piece itself is beautiful and the finish is immaculate.",
    name: "Seyi K.",
    meta: "Lace two-piece · Ibadan",
  },
];

export const REVIEWS_SUMMARY = {
  score: "4.9",
  count: 268,
  note: "Verified client reviews",
};

export const FAQS = [
  {
    q: "How do I order a made-to-measure piece?",
    a: "Add a piece to your bag and send your measurements at checkout, or book a fitting at our Victoria Island atelier. We confirm the cut with you before a single thread is moved.",
  },
  {
    q: "Are alterations really included?",
    a: "Yes. Every order includes one complimentary alteration within 14 days of delivery. Send the piece back and we will adjust the sleeve, waist or hem and return it free of charge.",
  },
  {
    q: "How long does delivery take?",
    a: "Lagos: 2–3 working days. Other Nigerian cities: 3–5 working days. Worldwide shipping is quoted at checkout and typically lands within 6–9 working days.",
  },
  {
    q: "Which payment methods do you accept?",
    a: "Card, bank transfer, POS at the atelier, and payment on pickup. For orders above ₦500,000 we accept a 50% deposit with the balance before delivery.",
  },
  {
    q: "Can I supply my own fabric?",
    a: "Absolutely. Bring your fabric to the atelier or have it delivered, and we will cut it into any design in the collection. Fittings are scheduled around your fabric arriving.",
  },
  {
    q: "How should I care for Aso Oke and Adire?",
    a: "Hand wash Adire in cold water separately for the first three washes. Aso Oke and lace should be dry cleaned. Every order ships with a printed care card.",
  },
];

export const CONTACT_REASONS = [
  "Book a fitting",
  "Made-to-measure order",
  "Alterations",
  "Wholesale & events",
  "Something else",
];
