/* Central content catalogue. Pure data — imported by both server and
   client components, so keep it serialisable (no functions). */

/* Hero looks come in pairs: `img` is the piece worn by a model, `formImg`
   is the same piece presented on a tailor's dress form — the runway stage
   wears one centre-stage and hangs the other in the product rail. `bg`
   tints the whole stage for that look; `tint` washes behind the rail card. */
export const HERO_SLIDES = [
  {
    id: "royal-blue-safari-suite",
    title: "Royal Blue Safari Suite",
    caption: "Safari suit · Short sleeve",
    look: "Look 01",
    collection: "Festive 2025",
    description:
      "Cut short in the sleeve with a half-canvas chest and four working pockets — the safari suit in its most confident colour.",
    bg: "#e7ecf2",
    img: "/images/royal-blue-safari-suite.png",
    formImg: "/images/royal-blue-safari-suite-form.png",
    width: 1024,
    height: 1024,
    formWidth: 736,
    formHeight: 736,
    tint: "rgba(47, 79, 143, 0.3)",
    alt: "Model wearing a royal blue short-sleeve safari suite",
    formAlt: "Royal blue safari suite displayed on a tailor's dress form",
    product: {
      name: "Royal Blue Safari Suite",
      note: "Short sleeve · half canvas",
      price: 245000,
      productId: "royal-blue-safari-suite",
    },
  },
  {
    id: "cream-embroidered-kaftan",
    title: "Cream Embroidered Kaftan",
    caption: "Embroidered · Short kaftan",
    look: "Look 02",
    collection: "Festive 2025",
    description:
      "A hand-trimmed neckline and a relaxed short line: the kaftan that carries every festive occasion.",
    bg: "#efece5",
    img: "/images/cream-offwhite-embroidered-kaftan-short.png",
    formImg: "/images/cream-offwhite-embroidered-kaftan-short-form.png",
    width: 922,
    height: 1152,
    formWidth: 736,
    formHeight: 920,
    tint: "rgba(194, 164, 125, 0.34)",
    alt: "Model wearing a cream off-white embroidered short kaftan",
    formAlt: "Cream embroidered short kaftan displayed on a tailor's dress form",
    product: {
      name: "Cream Embroidered Kaftan",
      note: "Hand-trimmed neckline",
      price: 198000,
      productId: "cream-offwhite-embroidered-kaftan",
    },
  },
  {
    id: "deep-burgundy-safari-suit",
    title: "Deep Burgundy Safari Suit",
    caption: "Safari suit · Tailored",
    look: "Look 03",
    collection: "Festive 2025",
    description:
      "Horn buttons, a slim cut and deep burgundy — tailoring that follows you from the altar to the after-party.",
    bg: "#efe7ea",
    img: "/images/deep-burgundy-safari-suit-short.png",
    formImg: "/images/deep-burgundy-safari-suit-short-form.png",
    width: 1024,
    height: 1024,
    formWidth: 736,
    formHeight: 736,
    tint: "rgba(109, 36, 54, 0.3)",
    alt: "Model wearing a deep burgundy short safari suit",
    formAlt: "Deep burgundy safari suit displayed on a tailor's dress form",
    product: {
      name: "Deep Burgundy Safari Suit",
      note: "Horn buttons · slim cut",
      price: 230000,
      productId: "deep-burgundy-safari-suit",
    },
  },
  {
    id: "medium-grey-high-collar",
    title: "Medium Grey High Collar",
    caption: "High collar · Patterned",
    look: "Look 04",
    collection: "Festive 2025",
    description:
      "A patterned weave on a banded collar. Quiet grey with a sharp shoulder and nothing left to prove.",
    bg: "#ebebeb",
    img: "/images/medium-grey-high-collar-pattern.png",
    formImg: "/images/medium-grey-high-collar-pattern-form.png",
    width: 976,
    height: 1102,
    formWidth: 736,
    formHeight: 831,
    tint: "rgba(122, 122, 122, 0.3)",
    alt: "Model wearing a medium grey patterned high-collar tunic",
    formAlt: "Medium grey high-collar pattern displayed on a tailor's dress form",
    product: {
      name: "Medium Grey High Collar",
      note: "Patterned weave · banded collar",
      price: 215000,
      productId: "medium-grey-high-collar",
    },
  },
  {
    id: "mustard-yellow-safari-suite",
    title: "Mustard Yellow Safari Suite",
    caption: "Safari suit · Statement",
    look: "Look 05",
    collection: "Festive 2025",
    description:
      "The statement piece of the season: short sleeve, confident mustard, impossible to miss.",
    bg: "#f2eee3",
    img: "/images/mustard-yellow-safari-suite-short.png",
    formImg: "/images/mustard-yellow-safari-suite-short-form.png",
    width: 1024,
    height: 1024,
    formWidth: 564,
    formHeight: 564,
    tint: "rgba(216, 161, 26, 0.32)",
    alt: "Model wearing a mustard yellow short safari suite",
    formAlt: "Mustard yellow safari suite displayed on a tailor's dress form",
    product: {
      name: "Mustard Yellow Safari Suite",
      note: "Short sleeve · statement cut",
      price: 225000,
      productId: "mustard-yellow-safari-suite",
    },
  },
  {
    id: "off-white-long-line-kaftan",
    title: "Off-White Long-Line Kaftan",
    caption: "Long line · Flowing",
    look: "Look 06",
    collection: "Festive 2025",
    description:
      "Ankle-length and flowing, with side slits that let the off-white cloth move with every step.",
    bg: "#eceef0",
    img: "/images/off-white-long-line-kaftan-long.png",
    formImg: "/images/off-white-long-line-kaftan-long-form.png",
    width: 922,
    height: 1152,
    formWidth: 1080,
    formHeight: 1324,
    tint: "rgba(233, 227, 216, 0.5)",
    alt: "Model wearing an off-white long-line kaftan",
    formAlt: "Off-white long-line kaftan displayed on a tailor's dress form",
    product: {
      name: "Off-White Long-Line Kaftan",
      note: "Ankle length · side slit",
      price: 175000,
      productId: "off-white-long-line-kaftan",
    },
  },
  {
    id: "dark-grey-safari-suite",
    title: "Dark Grey Safari Suite",
    caption: "Safari suit · Short sleeve",
    look: "Look 07",
    collection: "Festive 2025",
    description:
      "Soft shoulder, short sleeve, easy through the body — dark grey safari tailoring that works from day to night.",
    bg: "#e9e9ea",
    img: "/images/dark-grey-safari-suite-short-sleeve.png",
    formImg: "/images/dark-grey-safari-suite-short-sleeve-form.png",
    width: 1024,
    height: 1024,
    formWidth: 736,
    formHeight: 736,
    tint: "rgba(74, 74, 74, 0.3)",
    alt: "Model wearing a dark grey short-sleeve safari suite",
    formAlt: "Dark grey safari suite displayed on a tailor's dress form",
    product: {
      name: "Dark Grey Safari Suite",
      note: "Short sleeve · soft shoulder",
      price: 190000,
      productId: "dark-grey-safari-suite",
    },
  },
];

export const LOOKBOOK = [
  {
    num: "01",
    label: "01 / Kaftans",
    title: "Long-Sleeve\nKaftans",
    copy: "Charcoal, off-white and burgundy kaftans cut with a clean shoulder and finished with tonal embroidery at the chest and placket. Relaxed through the body so they move with you.",
    tags: ["Charcoal", "Off-White", "Burgundy"],
    cta: "Discover Kaftans",
    img: "/images/charcoal-kaftan-long-sleeve.jpg",
    width: 1080,
    height: 1338,
    alt: "Charcoal long-sleeve kaftan with tonal chest embroidery",
  },
  {
    num: "02",
    label: "02 / Long Sleeve",
    title: "Off-White\nLong Sleeves",
    copy: "An off-white long-sleeve native set with woven trim at the cuff and placket. The quiet piece of the collection — worn to fittings, dinners and everything in between.",
    tags: ["Woven Trim", "Native Set", "Off-White"],
    cta: "Explore Long Sleeves",
    img: "/images/offwhite-long-sleeve.jpg",
    width: 1080,
    height: 1324,
    alt: "Off-white long-sleeve native set with woven trim",
  },
  {
    num: "03",
    label: "03 / Short Sleeve",
    title: "Short-Sleeve\nEdit",
    copy: "Short sleeves cut for Lagos heat — dark green, charcoal and cream pieces that keep the structure of a tailored shoulder without the weight.",
    tags: ["Dark Green", "Short Sleeve", "Lagos Heat"],
    cta: "View Short Sleeve",
    img: "/images/dark-green-short-sleeved.jpg",
    width: 736,
    height: 831,
    alt: "Dark green short-sleeve native top",
  },
  {
    num: "04",
    label: "04 / Safari Suits",
    title: "Safari\nSuits",
    copy: "Four working pockets, a banded collar and a matching beret cap — the safari suit in burgundy, navy, mustard and grey, tailored short in the sleeve.",
    tags: ["Burgundy", "Beret Cap", "Short Sleeve"],
    cta: "Shop Safari Suits",
    img: "/images/burgundy-whine-safari-suit-berret-cap-short-sleeve.jpg",
    width: 736,
    height: 918,
    alt: "Burgundy short-sleeve safari suit with matching beret cap",
  },
];

export const ESSENTIALS = [
  {
    shape: "tile--xl",
    idx: "01",
    title: "Cream Short Kaftan",
    sub: "Embroidered neckline",
    img: "/images/cream-off-white-short-kaftan.jpg",
    width: 736,
    height: 806,
    alt: "Cream off-white short kaftan",
    filter: "Kaftan",
  },
  {
    shape: "tile--wide",
    idx: "02",
    title: "Striped Safari Suite",
    sub: "Collared, long sleeve",
    img: "/images/dark-brown-striped-suite-with-collar.jpg",
    width: 736,
    height: 693,
    alt: "Dark brown striped safari suite with collar",
    filter: "Safari Suit",
  },
  {
    shape: "tile--tall",
    idx: "03",
    title: "Burgundy Safari Suite",
    sub: "Short sleeve edit",
    img: "/images/burgundy-whine-safari-suite-short-sleeve.jpg",
    width: 736,
    height: 736,
    alt: "Burgundy wine short-sleeve safari suite",
    filter: "Safari Suit",
  },
  {
    shape: "tile--tall",
    idx: "04",
    title: "Navy Safari Suit",
    sub: "Short sleeve, working pockets",
    img: "/images/navy-blue-short-safari-suit.jpg",
    width: 736,
    height: 736,
    alt: "Navy blue short safari suit",
    filter: "Safari Suit",
  },
  {
    shape: "tile--wide",
    idx: "05",
    title: "Off-White Long Kaftan",
    sub: "Cut in our Lagos atelier",
    img: "/images/offwhite-kaftan-long.jpg",
    width: 736,
    height: 736,
    alt: "Off-white long kaftan",
    filter: "Kaftan",
  },
];

export const FILTERS = ["All", "Kaftan", "Safari Suit", "Tunic"];

export const PRODUCTS = [
  {
    id: "royal-blue-safari-suite",
    name: "Royal Blue Safari Suite",
    cat: "Safari Suit",
    price: 245000,
    compareAt: null,
    badge: "New",
    rating: 5,
    img: "/images/royal-blue-safari-suite.png",
    altImg: "/images/royal-blue-safari-suite-form.png",
    width: 1024,
    height: 1024,
    alt: "Royal blue short-sleeve safari suite",
    swatches: ["#2f4f8f", "#14110f", "#c2a47d"],
    desc: "A royal blue safari suite cut short in the sleeve and half-canvased through the chest, so it holds its line without feeling stiff. Four patch pockets, horn buttons, and a clean banded collar.",
  },
  {
    id: "cream-offwhite-embroidered-kaftan",
    name: "Cream Embroidered Kaftan",
    cat: "Kaftan",
    price: 198000,
    compareAt: null,
    badge: null,
    rating: 5,
    img: "/images/cream-offwhite-embroidered-kaftan-short.png",
    altImg: "/images/cream-offwhite-embroidered-kaftan-short-form.png",
    width: 922,
    height: 1152,
    alt: "Cream off-white embroidered short kaftan",
    swatches: ["#efe9df", "#c2a47d"],
    desc: "A short cream kaftan with hand-trimmed embroidery at the neckline and placket. Worn open over a vest or buttoned up — the piece that carries a whole evening.",
  },
  {
    id: "deep-burgundy-safari-suit",
    name: "Deep Burgundy Safari Suit",
    cat: "Safari Suit",
    price: 230000,
    compareAt: null,
    badge: null,
    rating: 5,
    img: "/images/deep-burgundy-safari-suit-short.png",
    altImg: "/images/deep-burgundy-safari-suit-short-form.png",
    width: 1024,
    height: 1024,
    alt: "Deep burgundy short safari suit",
    swatches: ["#6d2436", "#14110f"],
    desc: "Deep burgundy twill, slim through the body with a soft shoulder and horn buttons. Short sleeves keep it easy for Lagos heat; the colour keeps it formal.",
  },
  {
    id: "medium-grey-high-collar",
    name: "Medium Grey High-Collar Tunic",
    cat: "Tunic",
    price: 215000,
    compareAt: null,
    badge: null,
    rating: 4,
    img: "/images/medium-grey-high-collar-pattern.png",
    altImg: "/images/medium-grey-high-collar-pattern-form.png",
    width: 976,
    height: 1102,
    alt: "Medium grey patterned high-collar tunic",
    swatches: ["#8b8b8b", "#1c1917", "#c2a47d"],
    desc: "A medium grey patterned weave finished with a banded high collar. Structured enough for the boardroom, quiet enough to wear every week.",
  },
  {
    id: "mustard-yellow-safari-suite",
    name: "Mustard Yellow Safari Suite",
    cat: "Safari Suit",
    price: 225000,
    compareAt: null,
    badge: "New",
    rating: 5,
    img: "/images/mustard-yellow-safari-suite-short.png",
    altImg: "/images/mustard-yellow-safari-suite-short-form.png",
    width: 1024,
    height: 1024,
    alt: "Mustard yellow short safari suite",
    swatches: ["#d8a11a", "#c2a47d", "#14110f"],
    desc: "Mustard yellow, short sleeved, and cut for people who do not blend in. The statement safari suit of the festive edit — lined, pressed and finished in our Lagos atelier.",
  },
  {
    id: "off-white-long-line-kaftan",
    name: "Off-White Long-Line Kaftan",
    cat: "Kaftan",
    price: 175000,
    compareAt: null,
    badge: null,
    rating: 5,
    img: "/images/off-white-long-line-kaftan-long.png",
    altImg: "/images/off-white-long-line-kaftan-long-form.png",
    width: 922,
    height: 1152,
    alt: "Off-white long-line kaftan",
    swatches: ["#efe9df", "#c2a47d"],
    desc: "An ankle-length off-white kaftan with a fluid fall and side slits for movement. Featherweight, unlined through the body, and finished with a hand-rolled hem.",
  },
  {
    id: "dark-grey-safari-suite",
    name: "Dark Grey Safari Suite",
    cat: "Safari Suit",
    price: 190000,
    compareAt: 215000,
    badge: "Sale",
    rating: 4,
    img: "/images/dark-grey-safari-suite-short-sleeve.png",
    altImg: "/images/dark-grey-safari-suite-short-sleeve-form.png",
    width: 1024,
    height: 1024,
    alt: "Dark grey short-sleeve safari suite",
    swatches: ["#4a4a4a", "#14110f"],
    desc: "The everyday dark grey safari suite: short sleeve, soft shoulder, four working pockets. Cut generously enough to move in, tailored enough to meet a client in.",
  },
  {
    id: "aso-oke-set",
    name: "Cream Long-Sleeve Kaftan",
    cat: "Kaftan",
    price: 240000,
    compareAt: null,
    badge: "New",
    rating: 5,
    img: "/images/creame-offwite-kaftan-long-sleeve.jpg",
    altImg: "/images/cream-off-white-short-kaftan.jpg",
    width: 720,
    height: 900,
    alt: "Cream off-white long-sleeve kaftan",
    swatches: ["#efe9df", "#c2a47d", "#2f4f4f"],
    desc: "A cream long-sleeve kaftan with a clean placket and an easy, straight fall. Hand-finished in our Lagos atelier and cut to layer over a vest or wear on its own.",
  },
  {
    id: "embroidered-agbada",
    name: "Off-White Embroidered Kaftan",
    cat: "Kaftan",
    price: 285000,
    compareAt: null,
    badge: null,
    rating: 5,
    img: "/images/off-white-kaftan-simple-empbroidery.jpg",
    altImg: "/images/charcoal-kaftan-long-sleeve.jpg",
    width: 736,
    height: 1079,
    alt: "Off-white kaftan with simple embroidery",
    swatches: ["#f4f2ef", "#c2a47d", "#1c1917"],
    desc: "An off-white kaftan with quiet embroidery down the placket and a relaxed shoulder. Drapes cleanly over the body without losing its line.",
  },
  {
    id: "lace-occasion-gown",
    name: "Burgundy Short-Sleeve Safari Suit",
    cat: "Safari Suit",
    price: 395000,
    compareAt: 440000,
    badge: "Sale",
    rating: 5,
    img: "/images/burgundy-short-sleeve-safari-suite.jpg",
    altImg: "/images/burgundy-whine-safari-suite-short-sleeve.jpg",
    width: 735,
    height: 882,
    alt: "Burgundy short-sleeve safari suit",
    swatches: ["#c2a47d", "#7d2f43"],
    desc: "A burgundy safari suit with a sculpted shoulder, short sleeves and a clean banded collar. Built for weddings, receptions and the after-party.",
  },
  {
    id: "adire-indigo-ensemble",
    name: "Navy Long-Sleeve Kaftan",
    cat: "Kaftan",
    price: 185000,
    compareAt: null,
    badge: null,
    rating: 4,
    img: "/images/navy-blue-kaftan-long-sleeve.jpg",
    altImg: "/images/navy-blue-short-safari-suit.jpg",
    width: 736,
    height: 1353,
    alt: "Navy blue long-sleeve kaftan",
    swatches: ["#1f3a5f", "#f4f2ef"],
    desc: "A navy long-sleeve kaftan with a fluid fall and side slits. Deep colour, clean placket, finished by hand in the Lagos atelier.",
  },
  {
    id: "senator-three-piece",
    name: "Grey Long Kaftan",
    cat: "Kaftan",
    price: 225000,
    compareAt: null,
    badge: null,
    rating: 5,
    img: "/images/grey-long-kaftan-elegan-embroidery.jpg",
    altImg: "/images/burgundy-whine-safari-suit-berret-cap-short-sleeve.jpg",
    width: 736,
    height: 1342,
    alt: "Grey long kaftan with elegant embroidery",
    swatches: ["#14110f", "#2f4f4f", "#5c5651"],
    desc: "A grey long kaftan with tonal embroidery across the chest and a clean side slit. The everyday native piece, done properly.",
  },
  {
    id: "ankara-wax-two-piece",
    name: "Butter Cream Safari Suit",
    cat: "Safari Suit",
    price: 215000,
    compareAt: null,
    badge: "New",
    rating: 4,
    img: "/images/butter-cream-dark-brown-long-safari-suit.jpg",
    altImg: "/images/dark-brown-striped-suite-with-collar.jpg",
    width: 736,
    height: 736,
    alt: "Butter cream long safari suit with dark brown trousers",
    swatches: ["#c2a47d", "#7d2f43", "#2f4f4f"],
    desc: "A butter cream safari jacket over dark brown trousers. Soft shoulder, patch pockets and a collar that sits clean — lined so it holds its shape all evening.",
  },
  {
    id: "indigo-adire-wrap",
    name: "Navy Safari Suite",
    cat: "Safari Suit",
    price: 188000,
    compareAt: null,
    badge: null,
    rating: 5,
    img: "/images/navy-blue-safari-suite-long-sleeve.jpg",
    altImg: "/images/navy-blue-kaftan-long-sleeve.jpg",
    width: 736,
    height: 736,
    alt: "Navy blue long-sleeve safari suit",
    swatches: ["#1f3a5f"],
    desc: "A navy long-sleeve safari suit with a straight, easy line. Worn buttoned up for a fitting or open over a tee on the weekend.",
  },
  {
    id: "asooke-beaded-clutch",
    name: "Off-White Long-Stitch Kaftan",
    cat: "Kaftan",
    price: 168000,
    compareAt: null,
    badge: null,
    rating: 5,
    img: "/images/off-white-cream-long-stich-trimed.jpg",
    altImg: "/images/cream-off-white-short-kaftan.jpg",
    width: 500,
    height: 500,
    alt: "Off-white cream kaftan with long-stitch trim",
    swatches: ["#c2a47d", "#14110f"],
    desc: "An off-white cream kaftan traced with long-stitch trim down the front. Structured enough for a fitting, light enough for Lagos heat.",
  },
  {
    id: "embroidered-occasion-blouse",
    name: "Cream Short-Sleeve Kaftan",
    cat: "Kaftan",
    price: 145000,
    compareAt: null,
    badge: null,
    rating: 4,
    img: "/images/cream-short-sleeved-kaftan.jpg",
    altImg: "/images/burgundy-short-sleeve-safari-suite.jpg",
    width: 736,
    height: 918,
    alt: "Cream short-sleeve kaftan with embroidered neckline",
    swatches: ["#f4f2ef", "#c2a47d"],
    desc: "A cream short-sleeve kaftan with hand embroidery at the neckline. Pairs with a tailored trouser or a matching wrapper.",
  },
  {
    id: "silk-kaftan",
    name: "Dark Burgundy Kaftan",
    cat: "Kaftan",
    price: 165000,
    compareAt: 189000,
    badge: "Sale",
    rating: 5,
    img: "/images/dark-burgundy-kaftan.jpg",
    altImg: "/images/offwhite-kaftan-long.jpg",
    width: 736,
    height: 920,
    alt: "Dark burgundy kaftan with embroidered placket",
    swatches: ["#1c1917", "#c2a47d"],
    desc: "A dark burgundy kaftan with an embroidered placket and a mandarin collar — the piece for long evenings outdoors.",
  },
  {
    id: "adire-kimono-set",
    name: "Green Long Kaftan",
    cat: "Kaftan",
    price: 152000,
    compareAt: null,
    badge: null,
    rating: 4,
    img: "/images/green-long-kaftan.jpg",
    altImg: "/images/navy-blue-safari-suite-long-sleeve.jpg",
    width: 736,
    height: 690,
    alt: "Green long kaftan",
    swatches: ["#2f4f4f", "#f4f2ef"],
    desc: "A green long kaftan with a clean shoulder and an easy, straight fall — cut long enough to move in, finished with a hand-rolled hem.",
  },
  {
    id: "handwoven-cap",
    name: "Mustard Short-Sleeve Safari Suit",
    cat: "Safari Suit",
    price: 195000,
    compareAt: null,
    badge: null,
    rating: 5,
    img: "/images/muster-yellow-short-sleeve-safari-suit.jpg",
    altImg: "/images/grey-long-kaftan-elegan-embroidery.jpg",
    width: 564,
    height: 564,
    alt: "Mustard yellow short-sleeve safari suit",
    swatches: ["#14110f", "#c2a47d"],
    desc: "Mustard yellow, short sleeved and cut for people who do not blend in. Lined, pressed and finished in our Lagos atelier.",
  },
  {
    id: "lace-two-piece",
    name: "Grey Short-Sleeve Safari Suit",
    cat: "Safari Suit",
    price: 210000,
    compareAt: null,
    badge: null,
    rating: 5,
    img: "/images/grey-short-sleeve-safari-suit.jpg",
    altImg: "/images/burgundy-short-sleeve-safari-suite.jpg",
    width: 736,
    height: 736,
    alt: "Grey short-sleeve safari suit",
    swatches: ["#c2a47d", "#7d2f43"],
    desc: "A grey short-sleeve safari suit with a soft shoulder and four working pockets. Tailored enough to meet a client in, easy enough for the weekend — alterations included.",
  },
];

export const STORY = {
  eyebrow: "Our Story",
  title: "Crafted With Heritage",
  copy: "FASH began in Lagos with a simple idea: that the kaftans and safari suits we grew up seeing deserve to be made at the highest level. We work with embroiderers and tailors across Nigeria, then cut and finish every piece in our own atelier.",
  stats: [
    { value: 12, suffix: "", label: "Years of craft" },
    { value: 30, suffix: "+", label: "Artisan partners" },
    { value: 96, suffix: "%", label: "Repeat clients" },
  ],
  floatA: {
    img: "/images/grey-long-sleeve-simple-emboidery.jpg",
    width: 736,
    height: 672,
    alt: "Grey long-sleeve kaftan with simple embroidery",
  },
  floatB: {
    img: "/images/long-sleeve-dark-green-safari-suit.jpg",
    width: 736,
    height: 831,
    alt: "Long-sleeve dark green safari suit",
  },
};

export const HERO_STATS = [
  { dt: "Designs", value: 86 },
  { dt: "Fabrics", value: 34 },
  { dt: "Tailors", value: 24 },
];

export const REVIEWS = [
  {
    rating: 5,
    quote:
      "My kaftan arrived two days early and the fit was exact. The embroidery is cleaner than pieces I have paid triple for in London.",
    name: "Chidinma O.",
    meta: "Kaftan · London",
  },
  {
    rating: 5,
    quote:
      "They took my measurements over WhatsApp, cut the safari suit to fit, and handled two alterations without complaint. It felt like a private tailor.",
    name: "Emeka A.",
    meta: "Safari suit · Lagos",
  },
  {
    rating: 5,
    quote:
      "The embroidery is the real thing — you can tell it was done by hand. I get stopped every time I wear it.",
    name: "Funke B.",
    meta: "Embroidered kaftan · Abeokuta",
  },
  {
    rating: 5,
    quote:
      "Third order this year. Consistent quality, honest pricing, and the safari suits finish every outfit properly.",
    name: "Tunde O.",
    meta: "Menswear · Abuja",
  },
  {
    rating: 5,
    quote:
      "Booked a styling session before my wedding party. They pulled looks I would never have chosen and every piece landed.",
    name: "Amaka N.",
    meta: "Styling session · Port Harcourt",
  },
  {
    rating: 4,
    quote:
      "Delivery to Ibadan took an extra day, but the safari suit itself is beautiful and the finish is immaculate.",
    name: "Seyi K.",
    meta: "Safari suit · Ibadan",
  },
];

export const REVIEWS_SUMMARY = {
  score: "4.9",
  count: 268,
  note: "Verified client reviews",
};

export const FAQS = [
  {
    q: "How do I order a made-to-measure piece?",
    a: "Add a piece to your bag and send your measurements at checkout, or book a fitting at our Victoria Island atelier. We confirm the cut with you before a single thread is moved.",
  },
  {
    q: "Are alterations really included?",
    a: "Yes. Every order includes one complimentary alteration within 14 days of delivery. Send the piece back and we will adjust the sleeve, waist or hem and return it free of charge.",
  },
  {
    q: "How long does delivery take?",
    a: "Lagos: 2–3 working days. Other Nigerian cities: 3–5 working days. Worldwide shipping is quoted at checkout and typically lands within 6–9 working days.",
  },
  {
    q: "Which payment methods do you accept?",
    a: "Card, bank transfer, POS at the atelier, and payment on pickup. For orders above ₦500,000 we accept a 50% deposit with the balance before delivery.",
  },
  {
    q: "Can I supply my own fabric?",
    a: "Absolutely. Bring your fabric to the atelier or have it delivered, and we will cut it into any design in the collection. Fittings are scheduled around your fabric arriving.",
  },
  {
    q: "How should I care for kaftans and safari suits?",
    a: "Dry clean tailored safari suits, and press kaftans on the reverse at low heat so the embroidery sits flat. Every order ships with a printed care card.",
  },
];

export const CONTACT_REASONS = [
  "Book a fitting",
  "Made-to-measure order",
  "Alterations",
  "Wholesale & events",
  "Something else",
];
